### ISSUE TITLE
Correct usage of this library?

### ISSUE THREAD

**Issue by ItsMeThom-zz** [SachaMorard/phalcon-cassandra#1]
Hi @SachaMorard 
I've cloned your library and am successfully loading it in Phalcon, but Im having issues with how to correctly use the CassandraModel, would you mind giving me a brief explanation of how it works?

at the moment Im trying to call findFirst() on a model I extended from CassandraModel, and its outputting this:

Not implemented
#0 /var/www/html/cas/app/library/Phalcon/Db/Adapter/Cassandra.php(288): Cassandra\Cluster\Builder->build()
#1 /var/www/html/cas/app/library/Phalcon/Db/Adapter/Cassandra.php(179): Phalcon\Db\Adapter\Cassandra->_buildCluster(Array)
#2 /var/www/html/cas/app/config/services.php(157): Phalcon\Db\Adapter\Cassandra->__construct(Array)
#3 [internal function]: Closure->{closure}()
#4 [internal function]: Phalcon\Di\Service->resolve(NULL, Object(Phalcon\Di\FactoryDefault))
#5 /var/www/html/cas/app/library/Phalcon/Mvc/CassandraModel.php(69): Phalcon\Di->get('dbCassandra')
#6 /var/www/html/cas/app/models/TestModel.php(45): Phalcon\Mvc\CassandraModel::findFirst(Array)
#7 /var/www/html/cas/app/controllers/ApiController.php(40): TestModel::findFirst(Array)
#8 [internal function]: ApiController->storePayloadAction()
#9 [internal function]: Phalcon\Dispatcher->callActionMethod(Object(ApiController), 'storePayloadAct...', Array)
#10 [internal function]: Phalcon\Dispatcher->_dispatch()
#11 [internal function]: Phalcon\Dispatcher->dispatch()
#12 /var/www/html/cas/public/index.php(44): Phalcon\Mvc\Application->handle()
#13 {main}

**Comment by SachaMorard** [comment]
Hello

Yeah I'm sorry, I didn't have the time to write a good doc. But this library is working really good in production right now, on huge platforms. 

First of all, Which version of Cassandra, datastax php driver and sachoo/phalcon-cassandra do you use ?

**Comment by ItsMeThom-zz** [comment]
Hi Sasha,

Im using the following:

* Cassandra 3.2
* Php-driver 1.3.0
* phalcon-cassandra 1.3.0
* php 5.6

So far I've managed to get the supplied adapter working, I can connect to, and read/write from the cassandra DB using raw CQL commands, but Im a bit lost with the model, and how I should be using it. Im realtively new to Phalcon in general so I might be making a mistake with that.

**Comment by SachaMorard** [comment]
Hello

First of all you have to add and define some conf in your phalcon config file
```php
return new \Phalcon\Config([
    'cassandra' => [
        'adapter' => 'Cassandra',
        'hosts' => [ 'localhost'],
        'keyspace' => 'lobs',
        'consistency' => 'ONE', // Infos here \cassandra\ConsistencyLevel
        'retryPolicies' => 'DefaultPolicy',
    ]
]);
```


Then, you have to declare Cassandra service in your dependency injector : 

```php
/**
 * This service returns a Cassandra database
 */
$di->setShared('dbCassandra', function () {
    $config = $this->getConfig();
    $connection = new \Phalcon\Db\Adapter\Cassandra($config->cassandra->toArray());
    return $connection;
});
```

IMPORTANT, if you are using mysql too, you have to change the name of mysql service in **dbMysql**. For exemple:
```php
$di->setShared('dbMysql', function () {
    $config = $this->getConfig();
    $params = [
        'host' => $config->mysql->host,
        'port' => isset($config->mysql->port) ? $config->mysql->port : 3306,
        'username' => $config->mysql->username,
        'password' => $config->mysql->password,
        'dbname' => $config->mysql->dbname,
        'charset' => $config->mysql->charset
    ];
    return new \Phalcon\Db\Adapter\Pdo\Mysql($params);
});
```

Then, you just have to declare the correct database service to your models in @Source annotation. For exemple:
```php
<?php
namespace Models\Cassandra;

/**
 * Class Article
 * @package Models\Cassandra
 *
 * @Source('dbCassandra', 'article')
 */
class Article extends \Phalcon\Mvc\CassandraModel
{
    /**
     * @Primary
     * @Column(type="uuid", nullable=false)
     */
    public $uuid;

    /**
     * @Column(type="varchar", nullable=false)
     */
    public $title;

    /**
     * @Column(type="varchar", nullable=false)
     */
    public $description;

    /**
     * list<uuid>
     * uuid of linked articles
     * @Column(type="list", nullable=true)
     */
    public $links;

    /**
     * @Column(type="float", nullable=true)
     */
    public $lat;

    /**
     * @Column(type="float", nullable=true)
     */
    public $lon;

    /**
     * @Column(type="int", nullable=true)
     */
    public $radius;

    /**
     * @Column(type="varchar", nullable=false)
     */
    public $status;

    /**
     * @Column(type="varchar", nullable=false)
     */
    public $type;

    /**
     * @Column(type="varchar", nullable=false)
     */
    public $language;
}
```

I hope it will help. 
Best
Sacha

**Comment by ItsMeThom-zz** [comment]
Hi Sasha,

Thanks for the detailed reply, I think Im correctly understanding this now. However, one final issue;

Following from your example, I am getting the error: 
`Fatal error: Class 'Phalcon\Mvc\CassandraModel' not found in /var/www/html/ALSICAS/app/models/SerialModel.php on line 11`

Am I correct in thinking this is an autoloader issue? Im not too familiar with PSR-0 or how composer.json & autoloading works, but a quick investigation and dumping all registered classes shows me that -most- phalcon-cassandra classes are loaded correctly, but the model, coming from \Phaclon\Mvc\CassandraModel is not being loaded or registered correctly at all. Also, within db/adapter/Cassandra I have noticed three imports:
`use Cassandra\BatchStatement;
use Cassandra\Keyspace;
use Cassandra\Table;`

That dont appear to exist or be loaded anywhere. If its not too much trouble can you shed any light on this?


Thanks again for all the help.

Thom

**Comment by SachaMorard** [comment]
Hello

It seems you need to include autoload.php in your boostrap file. **require 'vendor/autoload.php';** For exemple:
```php
<?php

use Phalcon\Di\FactoryDefault;
use Phalcon\Mvc\Application;

define('BASE_PATH', dirname(__DIR__));

/**
 * The FactoryDefault Dependency Injector automatically registers the services that
 * provide a full stack framework. These default services can be overidden with custom ones.
 */
$di = new FactoryDefault();

require BASE_PATH . '/vendor/autoload.php';

/**
 * Include general services which defines $di
 */
require BASE_PATH . '/config/services.php';

/**
 * Include Autoloader, which is like composer autoloader but with Phalcon power
 */
include BASE_PATH . '/config/loader.php';

/**
 * Handle the request
 */
$application = new Application($di);
echo $application->handle()->getContent();
return;
```

**Comment by ItsMeThom-zz** [comment]
Thanks @SachaMorard You've been a huge help!

I have encountered another strange issue, and have a few questions with it.

Suppose I wanted to use Materialized Views, can this be done with phalcon-cassandra's models, or should I stick to raw CQL statements?

If I have a compound primary key (say its (day, month, year)) will CassandraModel correctly interpret the @primary tag for all three fields?

When I attempt a $model->save() call, its warning me that the preSave (Which is performing a "Select.." query is attempting data filtering, which cannot be done unless the query is ended with ALLOW FILTERING. Does Phalcon-Cassandra have a method to enable this query flag?

I owe you at least a few beers now Sacha :D

**Comment by SachaMorard** [comment]
Hi Thom

My answers bellow

> Thanks @SachaMorard <https://github.com/sachamorard> You've been a huge
> help!
>
> I have encountered another strange issue, and have a few questions with it.
>
> Suppose I wanted to use Materialized Views, can this be done with
> phalcon-cassandra's models, or should I stick to raw CQL statements?
>
yes, you have to use raw cql for that. It's a little be complicated to
transpose materialized views with models.

If I have a compound primary key (say its (day, month, year)) will
> CassandraModel correctly interpret the @primary
> <https://github.com/primary> tag for all three fields?
>
> Yeah, no problem. You just have to add @primary annotation to the model's
field you want. Be careful, order matters.

When I attempt a $model->save() call, its warning me that the preSave
> (Which is performing a "Select.." query is attempting data filtering, which
> cannot be done unless the query is ended with ALLOW FILTERING. Does
> Phalcon-Cassandra have a method to enable this query flag?
>
Save() method in orms is a chain of requests. Select (with filters), then
insert or update. But with Cassandra, it's not good to use UPDATE. And
select with Cassandra is way more complicated to use correctly than MySQL.
So my library follows the concepts of Cassandra. I always use insert()
method which is faster (a simple INSERT request)


>
I owe you at least a few beers now Sacha :D
>
it would be a pleasure, but I'm afraid you would have to do a long trip for
that (I'm in Paris) ;)

Best
Sacha

**Comment by SachaMorard** [comment]
I should say "I always use insert() method which is faster (a simple INSERT
request)"

**Comment by ItsMeThom-zz** [comment]
Thanks sacha! I think Im finally figuring this out. :)

Is there an implementation for the set<> type in DataTypes? For instance, can I define a property as `set<text>` or should I just use `set`?

**Comment by SachaMorard** [comment]
You can do it like that.

```php
/**
 * @Column(type="set", column="special_set")
 */
public $specialSet;

public static function newSpecialSet()
{
    return new \Cassandra\Set(\Cassandra::TYPE_TEXT);
}
```

**Comment by ItsMeThom-zz** [comment]
Hmm, I've tried to implement that, and tracing through the code, when CassandraModel calls _doLowInsert() to write the data, it returns succesful, but no actual data is getting written. This only seems to occur when I attempt to use a set<> field. Standard fields (int, text, etc) all work fine and the data is present as expected.

Edit: Its specifically happening in \Adapter\Cassabdra at the prepare($cqlstatement) call. Its throwing an exception 'unconfigured table array'. 

One of my parameters passed as values is an array, and the column in the model I have setup as a set<text> in the way you've described. Should I be preparing these values as a different type before sending them to the model? I was under the assumption i could pass it an array of values and in the case of the set type it would format them as expected.

Edit 2: Ive tracked it down a bit more, it seems to be triggering an Array to String conversion exception when binding the parameters to the cql query in cassandra->executePrepared(). Im not certain what I can do about this.
